version: '3'

services:

  broker-service_tcp:
    build:
      context: ./broker-service
      dockerfile: broker-service.dockerfile
    restart: always
    ports:
      - "8080:8081"
    deploy:
      mode: replicated
      replicas: 1
